// <auto-generated />
namespace eFormSqlController.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingMissingColumnsNotifications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingMissingColumnsNotifications));

        string IMigrationMetadata.Id
        {
            get { return "201704200702458_AddingMissingColumnsNotifications"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
