// <auto-generated />
namespace eFormSqlController.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingFieldValuesToCasesAndFieldsToCheckLists : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingFieldValuesToCasesAndFieldsToCheckLists));

        string IMigrationMetadata.Id
        {
            get { return "201708090934335_AddingFieldValuesToCasesAndFieldsToCheckLists"; }
        }

        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
