namespace Microting.eForm.Dto
{
    public enum Settings
    {
        firstRunDone,
        knownSitesDone,
        logLevel,
        logLimit,
        fileLocationPicture,
        fileLocationPdf,
        fileLocationJasper,
        token,
        comAddressApi,
        comAddressBasic,
        comAddressPdfUpload,
        comOrganizationId,
        awsAccessKeyId,
        awsSecretAccessKey,
        awsEndPoint,
        unitLicenseNumber,
        httpServerAddress,       
        maxParallelism,
        numberOfWorkers,
        comSpeechToText,
        swiftEnabled,
        swiftUserName,
        swiftPassword,
        swiftEndPoint,
        keystoneEndPoint,
        customerNo,
        s3Enabled,
        s3AccessKeyId,
        s3SecrectAccessKey,
        s3Endpoint
    }
}